[toolchain]
anchor_version = "0.32.1"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
init-if-needed = []
default = ["init-if-needed"]

[programs.localnet]
xnt_wrapper = "2Q8A2o2NkAeze9i38XJqMwdKNkygg52xK9HaXkSc539a"

[programs.devnet]
xnt_wrapper = "2Q8A2o2NkAeze9i38XJqMwdKNkygg52xK9HaXkSc539a"

[programs.mainnet]
xnt_wrapper = "2Q8A2o2NkAeze9i38XJqMwdKNkygg52xK9HaXkSc539a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "/home/ubuntu/xaddr/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
